"""Conservative Pass 4-local mappings into frozen report reasons.

Successful and not-applicable Pass 4 outcomes deliberately have no frozen
mapping.  A local digest mismatch is bounded diagnostic evidence, not numeric
confirmation or a global first-divergence result.
"""

from __future__ import annotations

from typing import Optional

from .pass4_contract import Pass4ReasonCode, Pass4Status


_PARTIAL = "partial_evidence_inconclusive"
_MALFORMED = "malformed_artifact"
_UNSUPPORTED = "unsupported_comparison"


LOCAL_REASON_TO_REPORT_REASON: dict[Pass4ReasonCode, str] = {
    Pass4ReasonCode.PARENT_STATUS_BLOCKED: _PARTIAL,
    Pass4ReasonCode.PARENT_ARTIFACT_MALFORMED: _MALFORMED,
    Pass4ReasonCode.PARENT_TYPED_ARTIFACT_INCOHERENT: _MALFORMED,
    Pass4ReasonCode.PARENT_COMPARISONS_TRUNCATED: _MALFORMED,
    Pass4ReasonCode.PARENT_LOCALIZATION_INCOHERENT: _MALFORMED,
    Pass4ReasonCode.PARENT_UPSTREAM_EVIDENCE_INCOHERENT: _MALFORMED,
    Pass4ReasonCode.DISCOVERY_REBOUND_LAYER_CHANGED: _PARTIAL,
    Pass4ReasonCode.DISCOVERY_REBOUND_SEMANTICS_CHANGED: _PARTIAL,
    Pass4ReasonCode.TRACE_SHA_MISMATCH: _MALFORMED,
    Pass4ReasonCode.SOURCE_ROLE_MISMATCH: _MALFORMED,
    Pass4ReasonCode.RUN_REPORT_BINDING_MISMATCH: _MALFORMED,
    Pass4ReasonCode.ARTIFACT_SET_BINDING_MISMATCH: _MALFORMED,
    Pass4ReasonCode.SEMANTIC_MANIFEST_BINDING_MISMATCH: _MALFORMED,
    Pass4ReasonCode.RUNTIME_CAPTURE_IDENTITY_MISMATCH: _MALFORMED,
    Pass4ReasonCode.NO_COMMON_CAPTURED_COORDINATES: _PARTIAL,
    Pass4ReasonCode.STEP_ALIGNMENT_MISMATCH: _UNSUPPORTED,
    Pass4ReasonCode.LAYER_ALIGNMENT_MISMATCH: _UNSUPPORTED,
    Pass4ReasonCode.PHASE_OR_POSITION_ALIGNMENT_MISMATCH: _UNSUPPORTED,
    Pass4ReasonCode.SHAPE_OR_COUNT_ALIGNMENT_MISMATCH: _UNSUPPORTED,
    Pass4ReasonCode.DTYPE_OR_PRECISION_ALIGNMENT_MISMATCH: _UNSUPPORTED,
    Pass4ReasonCode.STAGE_ROLE_OR_ORDER_ALIGNMENT_MISMATCH: _UNSUPPORTED,
    Pass4ReasonCode.COVERAGE_PARTITION_MALFORMED: _MALFORMED,
    Pass4ReasonCode.DUPLICATE_OR_OUT_OF_ORDER_COORDINATE: _MALFORMED,
    Pass4ReasonCode.SUMMARY_FIELD_MALFORMED: _MALFORMED,
    Pass4ReasonCode.DIGEST_FIELD_MALFORMED: _MALFORMED,
    Pass4ReasonCode.PROHIBITED_PAYLOAD_PRESENT: _MALFORMED,
    Pass4ReasonCode.DIGEST_CONTRACT_UNKNOWN: _UNSUPPORTED,
    Pass4ReasonCode.PARENT_CONTRACT_OR_FAMILY_UNSUPPORTED: _UNSUPPORTED,
    Pass4ReasonCode.PARENT_PHASE_UNSUPPORTED: _UNSUPPORTED,
    Pass4ReasonCode.PARENT_DIGEST_POLICY_UNSUPPORTED: _UNSUPPORTED,
    Pass4ReasonCode.INTRA_LAYOUT_OR_TAXONOMY_UNSUPPORTED: _UNSUPPORTED,
    Pass4ReasonCode.REQUESTED_STAGE_SET_UNSUPPORTED: _UNSUPPORTED,
}


SAFE_STATUS_TO_REPORT_REASON: dict[Pass4Status, str] = {
    Pass4Status.COMPARISON_BLOCKED_BY_PASS3: _PARTIAL,
    Pass4Status.INSUFFICIENT_COMMON_INTRA_LAYER_COVERAGE: _PARTIAL,
    Pass4Status.SOURCE_BINDING_INCONSISTENT: _MALFORMED,
    Pass4Status.CHECKPOINT_ALIGNMENT_INCONSISTENT: _UNSUPPORTED,
    Pass4Status.CHECKPOINT_SUMMARY_MALFORMED: _MALFORMED,
    Pass4Status.COMPARISON_POLICY_UNAVAILABLE: _UNSUPPORTED,
    Pass4Status.UNSUPPORTED_PARENT: _UNSUPPORTED,
    Pass4Status.UNSUPPORTED_INTRA_LAYER_LAYOUT: _UNSUPPORTED,
    Pass4Status.PARENT_REVALIDATION_INCONSISTENT: _PARTIAL,
}


def map_pass4_reason(code: Pass4ReasonCode) -> Optional[str]:
    return LOCAL_REASON_TO_REPORT_REASON.get(code)


def map_pass4_status(status: Pass4Status) -> Optional[str]:
    return SAFE_STATUS_TO_REPORT_REASON.get(status)
